### ISSUE TITLE
Error when turning off quest icons

### ISSUE THREAD

**Issue by Zaphod392** [Eternita-S/QuestAWAY#6]
Getting the error when I turned off some icons in 6.08:

```
QuestAWAY error] Destination is too short. (Parameter 'destination')
   at Lumina.Data.Files.TexFile.Convert(Span`1 src, Int32 width, Int32 height)
   at Lumina.Data.Files.TexFile.LoadFile()
   at Lumina.Data.SqPackStream.ReadFile[T](Int64 offset)
   at Lumina.Data.SqPack.ReadFile[T](Int64 offset)
   at Lumina.Data.Category.GetFile[T](ParsedFilePath path)
   at Lumina.Data.Repository.GetFile[T](Byte cat, ParsedFilePath path)
   at Dalamud.Data.DataManager.GetFile[T](String path) in C:\goatsoft\companysecrets\dalamud\Data\DataManager.cs:line 121
   at QuestAWAY.QuestAWAY.ImGuiDrawImage(String partialPath) in C:\VS\QuestAWAY\QuestAWAY\QuestAWAY.cs:line 91
```

**Comment by Zaphod392** [comment]
Wanted to add, this happens also when I open the addon window

**Comment by Limiana** [comment]
Hello. Hmm, can you please attach your `%appdata%\XIVLauncher\output.log`? 
**This log contains your ffxiv login, which you may want to edit out.**

**Comment by Limiana** [comment]
or well, just alternatively run integrity check in the xivlauncher instead

**Comment by Zaphod392** [comment]
`2022-03-01 06:43:26.263 -05:00 [INF] Trying to set up Loc for language code en
2022-03-01 06:43:26.339 -05:00 [INF] XIVLauncher started as xivlauncher-6.2.0.0-6.2.0-0-ge9d67e7
2022-03-01 06:43:26.339 -05:00 [INF] Starting update check...
2022-03-01 06:43:28.466 -05:00 [INF] Engaging Autologin...
2022-03-01 06:43:28.470 -05:00 [INF] [DUPDATE] Starting...
2022-03-01 06:43:28.530 -05:00 [INF] [DUPDATE] Using release version (6.3.0.4)
2022-03-01 06:43:31.142 -05:00 [INF] [DUPDATE] Now starting for .NET Runtime 5.0.6
2022-03-01 06:43:31.328 -05:00 [INF] [DUPDATE] All set for 2022.01.25.0000.0000
2022-03-01 06:46:59.313 -05:00 [INF] Trying to set up Loc for language code en
2022-03-01 06:46:59.391 -05:00 [INF] XIVLauncher started as xivlauncher-6.2.0.0-6.2.0-0-ge9d67e7
2022-03-01 06:46:59.391 -05:00 [INF] Starting update check...
2022-03-01 06:47:00.653 -05:00 [INF] Engaging Autologin...
2022-03-01 06:47:00.658 -05:00 [INF] [DUPDATE] Starting...
2022-03-01 06:47:01.139 -05:00 [INF] [DUPDATE] Using release version (6.3.0.4)
2022-03-01 06:47:01.235 -05:00 [INF] [DUPDATE] Now starting for .NET Runtime 5.0.6
2022-03-01 06:47:01.497 -05:00 [INF] [DUPDATE] All set for 2022.01.25.0000.0000
2022-03-01 06:47:06.729 -05:00 [INF] LoginToGame() called
2022-03-01 06:47:07.408 -05:00 [INF] XivGame::Login(steamServiceAccount:False, cache:False)
2022-03-01 06:47:07.408 -05:00 [INF] Cache is invalid or disabled, logging in normally.
2022-03-01 06:47:08.593 -05:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2022-03-01 06:47:10.380 -05:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:D:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn)
2022-03-01 06:47:10.383 -05:00 [INF] XivGame::LaunchGame(steamIntegration:False, steamServiceAccount:False, args:)
2022-03-01 06:47:10.384 -05:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:115558984 ticks:115558984 key:115539968
2022-03-01 06:47:10.389 -05:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"p"
2022-03-01 06:47:10.498 -05:00 [INF] [HOOKS] DalamudLauncher::Run(gp:D:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn, cl:"English", pid:16920)
2022-03-01 06:47:10.500 -05:00 [INF] [HOOKS] DelayInitializeMs: 0
2022-03-01 06:47:10.507 -05:00 [INF] [HOOKS] Started dalamud!
2022-03-01 06:47:12.958 -05:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyMi0wMy0wMVQwNjo0NzoxMi45NDEwODQ3LTA1OjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6dHJ1ZSwiSXNVaWRDYWNoZSI6ZmFsc2UsIkRhbGFtdWRFbmFibGVkIjp0cnVlLCJEYWxhbXVkTG9hZE1ldGhvZCI6MCwiRGFsYW11ZEluamVjdGlvbkRlbGF5IjowLjAsIlN0ZWFtSW50ZWdyYXRpb24iOmZhbHNlLCJFbmNyeXB0QXJndW1lbnRzIjp0cnVlLCJMYXVuY2hlclZlcnNpb24iOiI2LjIuMC4wIiwiTGF1bmNoZXJIYXNoIjoiNi4yLjAtMC1nZTlkNjdlNyIsIk9mZmljaWFsIjp0cnVlLCJEcGlBd2FyZW5lc3MiOjEsIlBsYXRmb3JtIjowLCJPYnNlcnZlZEdhbWVWZXJzaW9uIjoiMjAyMi4wMS4yNS4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MVZlcnNpb24iOiIyMDIxLjExLjIxLjAwMDAuMDAwMCIsIk9ic2VydmVkRXgyVmVyc2lvbiI6IjIwMjEuMTIuMTQuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDNWZXJzaW9uIjoiMjAyMS4xMi4xNC4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4NFZlcnNpb24iOiIyMDIyLjAxLjE4LjAwMDAuMDAwMCIsIkJja01hdGNoIjp0cnVlLCJJbmRleEludGVncml0eSI6MH0=`

**Comment by Zaphod392** [comment]
This was the latest section of the log

**Comment by Limiana** [comment]
This won't work unfortunately, I need the whole file

**Comment by Zaphod392** [comment]
[output.log](https://github.com/Eternita-S/QuestAWAY/files/8161398/output.log)

**Comment by Zaphod392** [comment]
uploaded and removed user info

**Comment by Limiana** [comment]
It seems like your game is corrupted. You will need to do either:
- An integrity check in xivlauncher, identify corrupted files and replace them manually with correct copies (if you provide list of corrupted files, I can send you original ones)
- Full game reinstall
- Try to use xivlauncher's repair game feature

You might succeed using start over textools' feature, however, I can't give you any instructions about it as I'm not familiar with that program.

**Comment by Zaphod392** [comment]
Yea its definitely when Textool is loaded, when removed I dont get the error. When I load up the UI changes it spits those errors
